# Generated by Django 2.0.6 on 2018-06-14 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'verbose_name': 'empresa', 'verbose_name_plural': 'empresas'},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'verbose_name': 'estudante', 'verbose_name_plural': 'estudantes'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'usuário', 'verbose_name_plural': 'usuários'},
        ),
        migrations.AddField(
            model_name='company',
            name='cnpj',
            field=models.CharField(default='', max_length=14),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='company_name',
            field=models.CharField(default='123', max_length=255),
            preserve_default=False,
        ),
    ]
