# Generated by Django 2.0.6 on 2018-07-08 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180613_2136'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('description', models.CharField(max_length=1024)),
                ('status', models.CharField(choices=[('REJECTED', 'Rejeitado'), ('PENDING', 'Pendente'), ('AVAILABLE', 'Disponível'), ('CLOSED', 'Encerrado')], max_length=8)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Company')),
            ],
        ),
    ]
