# Generated by Django 2.0.6 on 2018-07-10 00:11

from django.db import migrations


def create_company_user_group(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Permission = apps.get_model('auth', 'Permission')
    ContentType = apps.get_model('contenttypes', 'ContentType')

    Job = apps.get_model('core', 'Job')
    job_content_type = ContentType.objects.get_for_model(Job)
    all_job_permissions = Permission.objects.filter(content_type=job_content_type)

    group = Group.objects.create(name='Company')
    group.permissions.set(all_job_permissions)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20180709_2057'),
    ]

    operations = [
        migrations.RunPython(create_company_user_group)
    ]
