# Generated by Django 2.0.6 on 2018-07-10 00:33

from django.db import migrations


SKILL_LIST = [
    'Javascript',
    'Python',
    'C / C++',
    'Java',
    'Banco de Dados',
    '.NET',
    'Engenharia de Software',
    'Redes',
    'Analise de Requisitos',
    'Testes / QA',
]

def create_initial_skills(apps, schema_editor):
    Skill = apps.get_model('core', 'skill')

    for skill in SKILL_LIST:
        Skill.objects.create(title=skill)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20180709_2111'),
    ]

    operations = [
        migrations.RunPython(create_initial_skills)
    ]
