# Generated by Django 2.0.6 on 2018-07-10 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180709_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(default='', max_length=1024, verbose_name='Descrição'),
        ),
        migrations.AlterField(
            model_name='job',
            name='skills',
            field=models.ManyToManyField(to='core.Skill', verbose_name='Habilidades'),
        ),
    ]
