# Generated by Django 2.0.6 on 2018-07-09 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180708_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'verbose_name': 'estagio', 'verbose_name_plural': 'estagios'},
        ),
        migrations.AlterField(
            model_name='job',
            name='period',
            field=models.CharField(choices=[('MORNING', 'Manhã'), ('AFTERNOON', 'Tarde'), ('BOTH', 'Integral')], max_length=10, verbose_name='Período'),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('REJECTED', 'Rejeitado'), ('PENDING', 'Pendente'), ('AVAILABLE', 'Disponível'), ('CLOSED', 'Encerrado')], max_length=10, verbose_name='Status'),
        ),
    ]
