# Generated by Django 2.0.6 on 2018-07-09 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180709_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='application_date',
            field=models.DateField(verbose_name='Prazo de Inscrição'),
        ),
        migrations.AlterField(
            model_name='job',
            name='response_date',
            field=models.DateField(verbose_name='Data de Resposta'),
        ),
    ]
