# Generated by Django 2.0.6 on 2018-07-11 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20180710_2035'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='skills',
            field=models.ManyToManyField(to='core.Skill', verbose_name='Habilidades'),
        ),
    ]
