# Generated by Django 2.0.6 on 2018-07-11 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20180710_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, default='', max_length=1024, null=True, verbose_name='Descrição'),
        ),
    ]
