# Generated by Django 2.0.6 on 2018-07-11 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180710_2158'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='candidatos',
            field=models.ManyToManyField(blank=True, null=True, to='core.Student', verbose_name='Candidatos'),
        ),
    ]
