# Generated by Django 2.0.6 on 2018-07-11 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_job_candidatos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='candidatos',
            field=models.ManyToManyField(blank=True, to='core.Student', verbose_name='Candidatos'),
        ),
        migrations.AlterField(
            model_name='student',
            name='skills',
            field=models.ManyToManyField(blank=True, to='core.Skill', verbose_name='Habilidades'),
        ),
    ]
