# Generated by Django 2.0.6 on 2018-07-15 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20180711_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='escolhido',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Escolhido', to='core.Student', verbose_name='Escolhido'),
        ),
    ]
